version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  rsa-secure-dev.cyrhades.fr:
    image: anssi/fcsc2023-hardware-rsa-secure-dev:latest
    read_only: true
    ports:
      - ${PORT_SSH}:4000
